spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: m1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

